<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <!-- CommunityToolkit.Mvvm（源生成器，AOT/Trim 兼容） -->
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <!-- Avalonia 基础类型（用于 ThemeVariant 等） -->
  <ItemGroup>
    <PackageReference Include="Avalonia" />
  </ItemGroup>

  <!-- Microsoft 依赖注入与日志抽象（日志实现由主应用组合根提供） -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Tempds-build\DS.Tools.Core.dll" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Tempds-build\" />
  </ItemGroup>

</Project>
