<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Avalonia 生态系统 -->
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
  </ItemGroup>

  <ItemGroup>
    <!-- 资源文件 -->
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <!-- 样式文件 -->
    <AvaloniaResource Include="Styles\**" />
  </ItemGroup>
</Project>
