<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Cores\DS.Tools.Module.Base\DS.Tools.Module.Base.csproj" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Views\Base64View.axaml" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\ColorConverterView.axaml.cs">
        <DependentUpon>ColorConverterView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\DashboardView.axaml.cs">
        <DependentUpon>DashboardView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\JsonFormatterView.axaml.cs">
        <DependentUpon>JsonFormatterView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\PasswordGeneratorView.axaml.cs">
        <DependentUpon>PasswordGeneratorView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\TextHasherView.axaml.cs">
        <DependentUpon>TextHasherView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\TimestampConverterView.axaml.cs">
        <DependentUpon>TimestampConverterView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>

</Project>
